import * as XLSX from "xlsx";

export interface TseStock {
  symbol: string;
  name: string;
}

export interface TseStockDiff {
  added: TseStock[];
  removed: TseStock[];
  totalBefore: number;
  totalAfter: number;
  unchanged: number;
}

export const JPX_URL =
  "https://www.jpx.co.jp/markets/statistics-equities/misc/tvdivq0000001vg2-att/data_j.xls";

/**
 * JPX の Excel ファイルをダウンロードしてバッファを返す
 */
export async function downloadJpxExcel(): Promise<Buffer> {
  const res = await fetch(JPX_URL);
  if (!res.ok) {
    throw new Error(
      `JPXファイルのダウンロードに失敗: ${res.status} ${res.statusText}`,
    );
  }
  return Buffer.from(await res.arrayBuffer());
}

/**
 * Excel バッファをパースして TseStock[] を返す
 */
export function parseJpxExcel(buffer: Buffer): TseStock[] {
  const workbook = XLSX.read(buffer, { type: "buffer" });
  const sheetName = workbook.SheetNames[0];
  const sheet = workbook.Sheets[sheetName];
  const rows = XLSX.utils.sheet_to_json<(string | number | undefined)[]>(
    sheet,
    { header: 1 },
  );

  let headerRowIndex = -1;
  let codeColIndex = -1;
  let nameColIndex = -1;

  for (let i = 0; i < Math.min(rows.length, 5); i++) {
    const row = rows[i];
    if (!Array.isArray(row)) continue;
    for (let j = 0; j < row.length; j++) {
      const cell = String(row[j] || "").trim();
      if (cell === "コード") {
        headerRowIndex = i;
        codeColIndex = j;
      }
      if (cell === "銘柄名") {
        nameColIndex = j;
      }
    }
    if (headerRowIndex >= 0) break;
  }

  if (headerRowIndex < 0 || codeColIndex < 0 || nameColIndex < 0) {
    // フォールバック: 一般的な JPX フォーマット (日付, コード, 銘柄名, ...)
    headerRowIndex = 0;
    codeColIndex = 1;
    nameColIndex = 2;
  }

  const stocks: TseStock[] = [];
  const seen = new Set<string>();

  for (let i = headerRowIndex + 1; i < rows.length; i++) {
    const row = rows[i];
    if (!Array.isArray(row)) continue;

    const code = String(row[codeColIndex] || "").trim();
    const name = String(row[nameColIndex] || "").trim();

    if (!/^\d{4}$/.test(code)) continue;
    if (!name) continue;

    const symbol = `${code}.T`;
    if (seen.has(symbol)) continue;
    seen.add(symbol);

    stocks.push({ symbol, name });
  }

  stocks.sort((a, b) => a.symbol.localeCompare(b.symbol));
  return stocks;
}

/**
 * 現在のデータと新しいデータの差分を計算する
 */
export function computeDiff(
  current: TseStock[],
  fetched: TseStock[],
): TseStockDiff {
  const currentSet = new Set(current.map((s) => s.symbol));
  const fetchedSet = new Set(fetched.map((s) => s.symbol));

  const added = fetched.filter((s) => !currentSet.has(s.symbol));
  const removed = current.filter((s) => !fetchedSet.has(s.symbol));

  return {
    added,
    removed,
    totalBefore: current.length,
    totalAfter: fetched.length,
    unchanged: fetched.length - added.length,
  };
}

/**
 * TseStock[] を TypeScript ソースコードとして生成する
 */
export function generateTypeScriptContent(stocks: TseStock[]): string {
  const date = new Date().toISOString().split("T")[0];
  const entries = stocks
    .map(
      (s) =>
        `  { symbol: ${JSON.stringify(s.symbol)}, name: ${JSON.stringify(s.name)} }`,
    )
    .join(",\n");

  return `// This file is auto-generated by scripts/generate-tse-stocks.mjs
// Do not edit manually. Re-run the script to update.
// Generated: ${date}
// Total: ${stocks.length} stocks

export const TSE_STOCKS_METADATA = {
  generatedDate: "${date}",
  total: ${stocks.length},
} as const;

export const TSE_STOCKS: { symbol: string; name: string }[] = [
${entries},
];
`;
}
